application: stone-swallow
module: default
version: 20150202b
automatic_scaling:
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /script
  static_dir: script
- url: /html
  static_dir: html
- url: /lib
  static_dir: lib
- url: /.*
  script: _go_app
